# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_seed}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Monagle"]
  s.date = %q{2011-04-04}
  s.description = %q{Gives the ability to seed data by inserting it via activerecord. Also allows you to manage sets of data and seed based on the current environment.}
  s.email = %q{david.monagle@intrica.com.au}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/active_seed.rb",
    "lib/active_seed/engine.rb",
    "lib/active_seed/seed_csv.rb",
    "lib/generators/active_seed/active_seed_generator.rb",
    "lib/generators/active_seed/templates/development.yml",
    "lib/tasks/active_seed_tasks.rake"
  ]
  s.homepage = %q{http://www.intrica.com.au/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{Seeds data using activerecord.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

